id = "borealis-theme"
name = "Borealis"
version = "0.0.1"
schema_version = 1
authors = ["Ryan Eno"]
description = "An Elastic-inspired Borealis theme for Zed"
repository = "https://github.com/VimCommando/zed-theme-borealis"
